-- cc-mqtt tablet.lua | release dev | commit 64e4fdf | built 2026-07-24T23:59:51Z
-- Generated from src/targets/tablet.lua + src/lib/*.lua - do not edit directly.
--------------------------------------------------------------------
-- cc-mqtt tablet controller & dashboard for pocket computers
--------------------------------------------------------------------
local PROTOCOL     = "cbus"
local CONFIG_FILE  = "tablet.cfg"
local STALE_AFTER  = 8 -- s without update -> stale

--------------------------------------------------------------------
-- auto updater (runs ONLY on startup as requested)
--------------------------------------------------------------------
local Updater = (function()
--------------------------------------------------------------------
-- shared auto-updater
--
-- Used by every target (broker/controller/provider/subscriber
-- asynchronously via checkNow()/handleHttp(), tablet synchronously via
-- checkAndApplySync()) so this logic - and its bugs - exist exactly once.
--
-- Versions are GitHub Release tags (e.g. "v42"), not raw commit SHAs.
-- Three-stage state machine per check:
--   1. "release" - GET /repos/OWNER/REPO/releases/latest. One request
--      yields tag_name (the new version), each asset's download URL, and
--      the release body - which the build step fills with plain
--      "scriptname.lua: <hash>" lines, so this same response also gives
--      us the expected checksum for this script with no extra request.
--      tag_name == currentVersion -> done. Otherwise -> stage "asset".
--      Failure/unparseable -> stage "fallback".
--   2. "asset" - GET the release asset's browser_download_url, verify its
--      rolling-hash checksum against the one parsed in stage 1, apply on
--      match. Mismatch or fetch failure -> stage "fallback" (don't apply
--      on a bad checksum - a corrupted/partial download must not brick a
--      device).
--   3. "fallback" - GET raw main-branch content by filename and hash it
--      locally as the version, same as this module's predecessors already
--      did. Kept as a resilience path if Releases/assets ever misbehave,
--      and is also what carries a computer running the OLD (pre-release)
--      updater over to this one during the one-time migration window,
--      since main's raw files are still regenerated by CI on every push.
--------------------------------------------------------------------

local Updater = {}

local HTTP_HEADERS = {
  ["Cache-Control"] = "no-cache, no-store, must-revalidate",
  ["Pragma"]        = "no-cache",
  ["User-Agent"]    = "CC-Tweaked",
}

local function cacheBust()
  return os.epoch and os.epoch("utc") or (os.clock() * 1000)
end

local function getShortVer(v)
  if not v or v == "" then return "?" end
  if #v >= 7 then return v:sub(1, 7) end
  return v
end

-- Must stay bit-identical to scripts/build.py's fallback_hash() - that
-- script pre-computes this exact checksum for the release body / VERSION
-- docs, and this is also what a fallback-stage check hashes locally.
local function rollingHash(code)
  local hash = 0
  for i = 1, #code do hash = (hash * 31 + code:byte(i)) % 4294967296 end
  return string.format("%08x", hash)
end

local function escapePattern(s)
  return (s:gsub("[%(%)%.%%%+%-%*%?%[%]%^%$]", "%%%1"))
end

-- Parses a releases/latest API response body. Returns tagName, assetUrl,
-- checksum (checksum may be nil if the release body didn't have a parsable
-- line for this script - that's not fatal, see stage "asset" above).
local function parseReleaseResponse(raw, scriptName)
  local data = textutils.unserializeJSON(raw)
  if type(data) ~= "table" or type(data.tag_name) ~= "string" or type(data.assets) ~= "table" then
    return nil
  end
  local assetUrl
  for _, a in ipairs(data.assets) do
    if type(a) == "table" and a.name == scriptName then
      assetUrl = a.browser_download_url
    end
  end
  if not assetUrl then return nil end
  local checksum
  if type(data.body) == "string" then
    checksum = data.body:match(escapePattern(scriptName) .. ":%s*(%x+)")
  end
  return data.tag_name, assetUrl, checksum
end

-- opts = { scriptName, repoOwner, repoName, repoBranch, versionFile, updateTick }
function Updater.new(opts)
  local self = {}
  self.getShortVer = getShortVer
  local scriptName = opts.scriptName
  local repoOwner   = opts.repoOwner or "PrimeAPI"
  local repoName    = opts.repoName or "cc-mqtt"
  local repoBranch  = opts.repoBranch or "main"
  local versionFile = opts.versionFile or ".version"

  self.currentVersion = "dev"
  if fs.exists(versionFile) then
    local f = fs.open(versionFile, "r")
    if f then
      self.currentVersion = f.readAll():gsub("%s+", "")
      f.close()
    end
  end

  -- Short status word for a terminal/monitor header line, plus a full
  -- message printed to the console log. Checks used to fail completely
  -- silently, which made "http blocked" and "not due yet" indistinguishable.
  self.status = "never checked"
  local httpDisabledWarned = false

  -- { stage = "release"|"asset"|"fallback", url, tagName, checksum }
  local state = nil
  local stateStartedAt = nil
  -- http_success/http_failure normally resolve a request in well under a
  -- second, but if one never fires at all - a connection silently dropped
  -- rather than actively refused, for instance - state would otherwise
  -- stay non-nil forever, and checkNow()'s own "already checking" guard
  -- below would then silently no-op on every future call, including every
  -- later periodic tick. This bounds how long an in-flight check is
  -- trusted before checkNow() treats it as abandoned and starts fresh.
  local STATE_TIMEOUT = 20

  local function applyUpdate(version, code)
    local target = shell and shell.getRunningProgram() or "startup.lua"
    if not target or target == "" then target = "startup.lua" end

    -- Ensure startup.lua exists so rebooting always re-runs the script
    if target ~= "startup.lua" and target ~= "startup" then
      if not fs.exists("startup.lua") and not fs.exists("startup") then
        local sf = fs.open("startup.lua", "w")
        if sf then
          sf.writeLine('shell.run("' .. target .. '")')
          sf.close()
        end
      end
    end

    print("[Updater] Updating " .. target .. " and rebooting...")
    local f = fs.open(target .. ".tmp", "w")
    f.write(code)
    f.close()
    if fs.exists(target) then fs.delete(target) end
    fs.move(target .. ".tmp", target)

    local vf = fs.open(versionFile, "w")
    vf.write(version)
    vf.close()

    sleep(1)
    os.reboot()
  end

  local function fallbackUrl()
    return ("https://raw.githubusercontent.com/%s/%s/refs/heads/%s/%s?cb=%s")
      :format(repoOwner, repoName, repoBranch, scriptName, cacheBust())
  end

  local function releaseUrl()
    return ("https://api.github.com/repos/%s/%s/releases/latest?cb=%s")
      :format(repoOwner, repoName, cacheBust())
  end

  local function startFallback()
    state = { stage = "fallback", url = fallbackUrl() }
    stateStartedAt = os.clock()
    http.request(state.url, nil, HTTP_HEADERS)
  end

  function self.checkNow()
    if not http then
      self.status = "http disabled"
      if not httpDisabledWarned then
        httpDisabledWarned = true
        print("[Updater] the 'http' API is disabled on this server (or this")
        print("[Updater] computer isn't allowed to use it) - auto-update")
        print("[Updater] cannot work. Ask a server admin to enable http (and")
        print("[Updater] allow github.com/githubusercontent.com) in the")
        print("[Updater] CC:Tweaked server config.")
      end
      return
    end
    if state and stateStartedAt and (os.clock() - stateStartedAt) > STATE_TIMEOUT then
      print(("[Updater] previous %s check never resolved - abandoning it and starting over"):format(state.stage))
      state = nil
    end
    if state then return end -- already checking
    self.status = "checking"
    state = { stage = "release", url = releaseUrl() }
    stateStartedAt = os.clock()
    http.request(state.url, nil, HTTP_HEADERS)
  end

  -- fed http_success/http_failure events from the caller's main loop.
  -- "handle" is a response handle on http_success, but on http_failure
  -- CC:Tweaked passes the error message string in that same slot instead -
  -- captured here as the reason so a check failure is actually visible.
  function self.handleHttp(eventType, url, handle)
    if not state or url ~= state.url then return end

    if eventType == "http_failure" then
      -- "release" or "asset" failing (e.g. the release asset's
      -- browser_download_url redirects through a host - typically
      -- objects.githubusercontent.com - that isn't api.github.com or
      -- raw.githubusercontent.com, and may not be on this Minecraft
      -- server's http allowlist even when those two are) still has a way
      -- forward: the raw-content fallback. Only a "fallback" failure is
      -- truly terminal - there's nowhere else left to try.
      if state.stage == "release" or state.stage == "asset" then
        startFallback()
      else
        self.status = "check failed"
        print(("[Updater] %s check failed: %s"):format(state.stage, tostring(handle)))
        state = nil
      end
      return
    end

    if state.stage == "release" then
      local raw = handle.readAll()
      handle.close()
      local tagName, assetUrl, checksum = parseReleaseResponse(raw, scriptName)
      if not tagName then
        startFallback()
        return
      end
      if tagName == self.currentVersion then
        self.status = "up to date"
        state = nil
        return
      end
      self.status = "updating"
      print(("[Updater] New version detected (%s -> %s)!"):format(getShortVer(self.currentVersion), getShortVer(tagName)))
      state = { stage = "asset", url = assetUrl, tagName = tagName, checksum = checksum }
      stateStartedAt = os.clock()
      http.request(state.url, nil, HTTP_HEADERS)

    elseif state.stage == "asset" then
      local code = handle.readAll()
      handle.close()
      if state.checksum and rollingHash(code) ~= state.checksum then
        print("[Updater] asset checksum mismatch, falling back to raw content")
        startFallback()
        return
      end
      local tagName = state.tagName
      state = nil
      applyUpdate(tagName, code)

    elseif state.stage == "fallback" then
      local code = handle.readAll()
      local headers = handle.getResponseHeaders()
      handle.close()
      local etag = headers and (headers["ETag"] or headers["etag"] or headers["Etag"])
      local version = etag and etag:match("(%x%x%x%x%x%x%x+)")
      if not version then version = rollingHash(code) end
      state = nil
      if version == self.currentVersion then
        self.status = "up to date"
      else
        self.status = "updating"
        applyUpdate(version, code)
      end
    end
  end

  -- Blocking one-shot check+apply for callers (tablet.lua) that only ever
  -- check once at startup, deliberately before opening rednet - there's no
  -- live network traffic to protect there, so a bounded blocking wait is
  -- fine and simpler than driving the async state machine for a single
  -- check. Reuses the exact same URL building / parsing / checksum / apply
  -- logic as the async path above - written once either way.
  function self.checkAndApplySync(timeoutSec)
    if not http then
      return false, "http disabled"
    end
    timeoutSec = timeoutSec or 10

    local function awaitHttp(url)
      http.request(url, nil, HTTP_HEADERS)
      local timer = os.startTimer(timeoutSec)
      while true do
        local ev = { os.pullEvent() }
        if ev[1] == "http_success" and ev[2] == url then
          return true, ev[3]
        elseif ev[1] == "http_failure" and ev[2] == url then
          return false, ev[3]
        elseif ev[1] == "timer" and ev[2] == timer then
          return false, "timeout"
        end
      end
    end

    local relOk, relRes = awaitHttp(releaseUrl())
    local tagName, assetUrl, checksum
    if relOk then
      local raw = relRes.readAll()
      relRes.close()
      tagName, assetUrl, checksum = parseReleaseResponse(raw, scriptName)
    end

    if tagName then
      if tagName == self.currentVersion then return false, "up to date" end
      local assetOk, assetRes = awaitHttp(assetUrl)
      if assetOk then
        local code = assetRes.readAll()
        assetRes.close()
        if not checksum or rollingHash(code) == checksum then
          applyUpdate(tagName, code) -- reboots, does not return
        end
      end
      -- asset fetch failed or checksum mismatch -> fall through to fallback
    end

    local fbOk, fbRes = awaitHttp(fallbackUrl())
    if not fbOk then return false, "check failed" end
    local code = fbRes.readAll()
    local headers = fbRes.getResponseHeaders()
    fbRes.close()
    local etag = headers and (headers["ETag"] or headers["etag"] or headers["Etag"])
    local version = etag and etag:match("(%x%x%x%x%x%x%x+)") or rollingHash(code)
    if version == self.currentVersion then return false, "up to date" end
    applyUpdate(version, code) -- reboots, does not return
  end

  return self
end

return Updater
end)()

local updater = Updater.new({ scriptName = "tablet.lua" })
-- checkAndApplySync() reuses the exact same URL building / parsing /
-- checksum / apply logic as the async broker/controller/provider/
-- subscriber path, just driven with a blocking wait instead of an event-
-- driven state machine - appropriate here since this check deliberately
-- runs only once at startup, before rednet.open(), so there's no live
-- network traffic to protect. See src/lib/updater.lua for the shared
-- implementation.

--------------------------------------------------------------------
-- configuration management
--------------------------------------------------------------------
local cfg = {
  name = "Tablet",
  metrics = {},      -- list of { entity = "matrix1", key = "energy", label = "Energy" }
  quickActions = {}, -- list of { entity = "fission1", action = "scram", label = "SCRAM REACTOR", args = nil }
}

local function saveConfig()
  local f = fs.open(CONFIG_FILE, "w")
  if f then
    f.write(textutils.serialize(cfg))
    f.close()
  end
end

local function loadConfig()
  if fs.exists(CONFIG_FILE) then
    local f = fs.open(CONFIG_FILE, "r")
    if f then
      local data = textutils.unserialize(f.readAll())
      f.close()
      if type(data) == "table" then
        cfg = data
        cfg.metrics = cfg.metrics or {}
        cfg.quickActions = cfg.quickActions or {}
      end
    end
  end
end

--------------------------------------------------------------------
-- rednet & network management
--------------------------------------------------------------------
if not rednet then error("Rednet API required", 0) end

local function openModem()
  for _, side in ipairs(peripheral.getNames()) do
    if peripheral.getType(side) == "modem" then
      if not rednet.isOpen(side) then rednet.open(side) end
      return true
    end
  end
  return false
end

openModem()

local broker = nil
local ents = {}     -- { entityName = { data = {}, meta = {}, lastSeen = timestamp, kind = "" } }
local registry = {} -- { entityName = { kind = "", online = bool } }

local function findBroker()
  local id = rednet.lookup(PROTOCOL, "broker")
  if id then broker = id return true end
  return false
end

local function send(msg)
  if not broker then findBroker() end
  if broker then
    rednet.send(broker, msg, PROTOCOL)
  end
end

local function subscribe()
  send({ type = "subscribe", topics = { "#" }, version = updater.currentVersion })
end

local function requestRegistry()
  send({ type = "req_registry" })
end

local function sendCommand(entity, action, args)
  send({ type = "command", entity = entity, action = action, args = args })
end

local function handleNet(msg, senderId)
  if type(msg) ~= "table" then return end

  if msg.type == "broker_online" or msg.type == "reannounce_req" then
    if senderId then broker = senderId end
    subscribe()
    requestRegistry()

  elseif msg.type == "data" and msg.entity then
    ents[msg.entity] = ents[msg.entity] or {}
    local e = ents[msg.entity]
    e.data = msg.data
    e.lastSeen = os.clock()
    e.stale = false
    if msg.topic then e.kind = msg.topic:match("^([^/]+)/") or e.kind end
    if msg.actions and #msg.actions > 0 then e.actions = msg.actions end

  elseif msg.type == "registry" and msg.entities then
    for name, info in pairs(msg.entities) do
      local acts = info.actions or (info.meta and info.meta.actions) or {}
      registry[name] = {
        kind = info.kind,
        online = info.online,
        actions = acts,
        meta = info.meta
      }
      ents[name] = ents[name] or {}
      ents[name].kind = info.kind or ents[name].kind
      ents[name].meta = info.meta or ents[name].meta
      if #acts > 0 then ents[name].actions = acts end
    end

  elseif msg.type == "cmdResult" then
    return msg.entity, msg.action, msg.result, msg.error
  end
end

local function getEntityActions(name)
  local e = ents[name]
  local reg = registry[name]
  if e and e.actions and #e.actions > 0 then return e.actions end
  if e and e.meta and e.meta.actions and #e.meta.actions > 0 then return e.meta.actions end
  if reg and reg.actions and #reg.actions > 0 then return reg.actions end
  if reg and reg.meta and reg.meta.actions and #reg.meta.actions > 0 then return reg.meta.actions end
  return {}
end

local function getSortedEntities()
  local sorted = {}
  for n in pairs(registry) do sorted[#sorted + 1] = n end
  for n in pairs(ents) do
    if not registry[n] then
      local found = false
      for _, x in ipairs(sorted) do if x == n then found = true break end end
      if not found then sorted[#sorted + 1] = n end
    end
  end
  table.sort(sorted)
  return sorted
end

local function getEntityFields(name)
  local fields = {}
  local e = ents[name]
  if e and e.data then
    for k in pairs(e.data) do
      if k:sub(1, 1) ~= "_" then fields[#fields + 1] = k end
    end
    table.sort(fields)
  end
  if #fields == 0 then
    fields = { "percent", "energy", "maxEnergy", "input", "output", "status", "temp", "fuel", "coolant", "waste", "amount" }
  end
  return fields
end

--------------------------------------------------------------------
-- formatting helpers
--------------------------------------------------------------------
local function si(n)
  if type(n) ~= "number" then return tostring(n or "?") end
  local a = math.abs(n)
  if a >= 1e12 then return string.format("%.2fT", n / 1e12) end
  if a >= 1e9  then return string.format("%.2fG", n / 1e9)  end
  if a >= 1e6  then return string.format("%.2fM", n / 1e6)  end
  if a >= 1e3  then return string.format("%.1fk", n / 1e3)  end
  return string.format("%.0f", n)
end

local function fmtUnit(n, unit)
  if type(n) ~= "number" then return tostring(n or "?") end
  local a, prefix = math.abs(n), ""
  local v = n
  if a >= 1e12 then v, prefix = n / 1e12, "T"
  elseif a >= 1e9 then v, prefix = n / 1e9, "G"
  elseif a >= 1e6 then v, prefix = n / 1e6, "M"
  elseif a >= 1e3 then v, prefix = n / 1e3, "k" end
  local num = string.format(prefix == "" and "%.0f" or "%.2f", v)
  return num .. " " .. prefix .. (unit or "")
end

local function formatSmartValue(key, val)
  if type(val) == "number" then
    local kLower = key:lower()
    if (val >= 0 and val <= 1) and (kLower:find("percent") or kLower:find("fill") or kLower == "fuel" or kLower == "coolant" or kLower == "waste" or kLower == "damage" or kLower == "steam" or kLower == "energy") then
      local pct = math.floor(val * 100 + 0.5)
      local fill = math.floor(val * 7 + 0.5)
      local bar = "[" .. string.rep("#", fill) .. string.rep("-", 7 - fill) .. "]"
      local isDanger = kLower:find("damage") or kLower:find("waste") or (kLower:find("temp") and val > 0.8)
      return bar .. string.format(" %2d%%", pct), isDanger and colors.red or colors.lime
    elseif kLower:find("energy") or kLower:find("maxenergy") then
      return fmtUnit(val, "FE"), colors.lime
    elseif kLower:find("input") or kLower:find("output") or kLower:find("net") or kLower:find("prod") then
      local s = val >= 0 and "+" or ""
      return s .. fmtUnit(val, "FE/t"), (val >= 0 and colors.lime or colors.red)
    elseif kLower:find("flow") or kLower:find("burn") or kLower:find("rate") then
      return fmtUnit(val, "mB/t"), colors.yellow
    elseif kLower:find("fluid") or kLower:find("steam") or kLower:find("coolant") or kLower:find("waste") or kLower:find("amount") then
      return fmtUnit(val, "mB"), colors.cyan
    elseif kLower:find("temp") then
      return string.format("%.1f K", val), (val > 1000 and colors.red or colors.yellow)
    else
      return si(val), colors.white
    end
  else
    local sVal = tostring(val or "?")
    local sUpper = sVal:upper()
    if sUpper:find("RUNNING") or sUpper:find("ACTIVE") or sUpper:find("ONLINE") or sUpper == "TRUE" then
      return sVal, colors.lime
    elseif sUpper:find("SCRAM") or sUpper:find("OFFLINE") or sUpper:find("DISABLED") or sUpper == "FALSE" then
      return sVal, colors.red
    else
      return sVal, colors.white
    end
  end
end

--------------------------------------------------------------------
-- UI state & non-flicker rendering engine
--------------------------------------------------------------------
local activeTab       = "DASHBOARD" -- "DASHBOARD", "ACTIONS", "ENTITIES", "SETTINGS", "SETTINGS_METRICS", "SETTINGS_ACTIONS", "INSPECT", "WIZARD_ENTITY", "WIZARD_FIELD", "WIZARD_ACTION", "INPUT_ACTION_NAME", "INPUT_ARG", "RENAME_METRIC"
local inspectEntity   = nil
local inspectScroll   = 1
local selectedAction  = nil
local editMetricIdx   = nil
local inputBuffer     = ""
local statusBanner    = nil

-- Add Metric/Action wizard state
local wizardEntity    = nil
local wizardField     = nil
local wizardTarget    = nil -- "METRIC" or "ACTION"
local wizardCustomAction = false -- true while INPUT_ARG is collecting args for a new custom quick action

-- Heartbeat animation frames
local animFrames      = { "O", "o", ".", "o" }
local animIdx         = 1

local function setBanner(msg, isError)
  statusBanner = { text = msg, error = isError or false, time = os.clock() }
end

local function padLine(str, w)
  str = tostring(str or "")
  if #str > w then return str:sub(1, w) end
  return str .. string.rep(" ", w - #str)
end

-- Single source of truth for Inspect-screen row positions, shared by
-- renderScreen and handleTouch so the two can never drift apart.
local function computeInspectLayout(entityName)
  local e = ents[entityName]
  local keys = {}
  if e and e.data then
    for k in pairs(e.data) do if k:sub(1, 1) ~= "_" then keys[#keys + 1] = k end end
    table.sort(keys)
  end

  inspectScroll = math.max(1, math.min(inspectScroll, math.max(1, #keys - 4)))

  local scrollUpShown = inspectScroll > 1
  local maxValLines = scrollUpShown and 4 or 5
  local endIdx = math.min(#keys, inspectScroll + maxValLines - 1)
  local rowsDrawn = math.max(0, endIdx - inspectScroll + 1)
  local valStartY = scrollUpShown and 5 or 4
  local scrollDownShown = endIdx < #keys
  local scrollDownY = valStartY + rowsDrawn

  local y = scrollDownY
  if scrollDownShown then y = y + 1 end
  y = math.max(y, 11)
  local actStartY = y + 1

  return {
    keys = keys,
    scrollUpShown = scrollUpShown,
    maxValLines = maxValLines,
    endIdx = endIdx,
    rowsDrawn = rowsDrawn,
    valStartY = valStartY,
    scrollDownShown = scrollDownShown,
    scrollDownY = scrollDownY,
    actionsHeaderY = y,
    actStartY = actStartY,
  }
end

--------------------------------------------------------------------
-- screens rendering
--------------------------------------------------------------------
local function renderScreen()
  local w, h = term.getSize()
  term.setBackgroundColor(colors.black)
  term.clear()

  if statusBanner and (os.clock() - statusBanner.time > 5) then
    statusBanner = nil
  end

  -- Header Bar (Line 1)
  term.setCursorPos(1, 1)
  term.setBackgroundColor(colors.blue)
  term.setTextColor(colors.white)
  local animChar = animFrames[animIdx]
  local headText = (" [%s] Tablet (v:%s)"):format(animChar, updater.getShortVer(updater.currentVersion))
  local bText    = ("#%s "):format(broker and tostring(broker) or "?")
  local space    = math.max(1, w - #headText - #bText)
  term.write(headText .. string.rep(" ", space) .. bText)

  -- Content Area (Lines 2 to h-1)
  if activeTab == "DASHBOARD" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" METRICS DASHBOARD", w))

    local y = 3
    if #cfg.metrics == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("No metrics added yet.")
      term.setCursorPos(2, 5)
      term.write("Go to Settings [Cfg] to add!")
    else
      for _, m in ipairs(cfg.metrics) do
        if y >= h - 1 then break end
        local ent = ents[m.entity]
        local val = ent and ent.data and ent.data[m.key]

        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.black)

        -- Strict 25-char max line length to prevent CC terminal auto-wrap cursor shift
        local maxLineW = math.min(25, w - 1)
        local lblW = 6 -- 5 chars + 1 space = 6 chars
        local availW = math.max(8, maxLineW - lblW)

        -- 1. Custom Label Column (5 chars max)
        term.setTextColor(colors.cyan)
        local rawLabel = m.label or m.entity
        local displayLabel = rawLabel:sub(1, 5)
        term.write(displayLabel .. string.rep(" ", math.max(1, lblW - #displayLabel)))

        -- 2. Value / Smooth Color Block Bar Area
        if not ent or not ent.data then
          term.setTextColor(colors.gray)
          term.write("offline")
        elseif type(val) == "number" then
          local kLower = m.key:lower()
          if (val >= 0 and val <= 1) and (kLower:find("percent") or kLower:find("fill") or kLower == "fuel" or kLower == "coolant" or kLower == "waste" or kLower == "damage" or kLower == "steam" or kLower == "charge") then
            local pct = math.floor(val * 100 + 0.5)
            local pctStr = string.format("%3d%%", pct)
            local barW = math.max(3, availW - #pctStr - 1)
            local fill = math.floor(val * barW + 0.5)
            local isDanger = kLower:find("damage") or kLower:find("waste") or (kLower:find("temp") and val > 0.8)

            term.setBackgroundColor(isDanger and colors.red or colors.lime)
            term.write(string.rep(" ", fill))
            term.setBackgroundColor(colors.gray)
            term.write(string.rep(" ", barW - fill))
            term.setBackgroundColor(colors.black)
            term.setTextColor(colors.white)
            term.write(" " .. pctStr)
          else
            local formatted, valColor = formatSmartValue(m.key, val)
            term.setTextColor(valColor)
            term.write(formatted:sub(1, availW))
          end
        else
          local formatted, valColor = formatSmartValue(m.key, val)
          term.setTextColor(valColor)
          term.write(formatted:sub(1, availW))
        end

        local cx, _ = term.getCursorPos()
        if cx <= w then term.write(string.rep(" ", w - cx + 1)) end
        y = y + 1
      end
    end

    -- fill empty body lines cleanly without flickering
    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "ACTIONS" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" QUICK ACTIONS", w))

    local y = 3
    if #cfg.quickActions == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("No quick actions configured.")
      term.setCursorPos(2, 5)
      term.write("Go to Settings [Cfg] to add!")
    else
      for idx, qa in ipairs(cfg.quickActions) do
        if y >= h - 1 then break end
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.black)
        term.setTextColor(colors.white)

        local btnText = (" [%d] %s"):format(idx, qa.label or qa.action)
        term.setBackgroundColor(colors.gray)
        term.setTextColor(colors.white)
        term.write(padLine(btnText, w - 2))
        term.setBackgroundColor(colors.black)
        term.write(" ")
        y = y + 2
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "ENTITIES" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" REGISTERED ENTITIES", w))

    local sorted = {}
    for n in pairs(registry) do sorted[#sorted + 1] = n end
    for n in pairs(ents) do if not registry[n] then sorted[#sorted + 1] = n end end
    table.sort(sorted)

    local y = 3
    if #sorted == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("Waiting for entities...")
    else
      for _, name in ipairs(sorted) do
        if y >= h - 1 then break end
        local e = ents[name]
        local reg = registry[name]
        local isOnline = (e and e.lastSeen and (os.clock() - e.lastSeen <= STALE_AFTER)) or (reg and reg.online)

        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.black)
        term.setTextColor(isOnline and colors.lime or colors.red)
        term.write(isOnline and " * " or " x ")

        term.setTextColor(colors.white)
        local padName = name .. string.rep(" ", math.max(1, 14 - #name))
        term.write(padName:sub(1, 14))

        term.setTextColor(colors.lightGray)
        local k = (e and e.kind) or (reg and reg.kind) or "dev"
        term.write(k:sub(1, w - 18))

        local cx, _ = term.getCursorPos()
        if cx <= w then term.write(string.rep(" ", w - cx + 1)) end
        y = y + 1
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "INSPECT" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" ENTITY: " .. tostring(inspectEntity), w))

    local y = 3
    local e = ents[inspectEntity]
    if not e then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.red)
      term.write("No data available.")
    else
      local layout = computeInspectLayout(inspectEntity)
      local keys = layout.keys

      term.setCursorPos(1, y)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.cyan)
      term.write((" TELEMETRY (%d fields):"):format(#keys))
      y = y + 1

      if layout.scrollUpShown then
        term.setCursorPos(2, y)
        term.setTextColor(colors.yellow)
        term.write("^ tap to scroll up ^")
        y = y + 1
      end

      for i = inspectScroll, layout.endIdx do
        local k = keys[i]
        local val = e.data[k]
        local formatted, valColor = formatSmartValue(k, val)

        term.setCursorPos(2, y)
        term.setTextColor(colors.lightGray)
        local keyLabel = k:sub(1, 8)
        term.write(keyLabel .. ": ")

        term.setTextColor(valColor)
        term.write(formatted:sub(1, math.max(1, w - 17)))

        term.setCursorPos(w - 5, y)
        term.setBackgroundColor(colors.green)
        term.setTextColor(colors.white)
        term.write("[+Dash]")
        term.setBackgroundColor(colors.black)
        y = y + 1
      end

      if layout.scrollDownShown then
        term.setCursorPos(2, y)
        term.setTextColor(colors.yellow)
        term.write("v tap to scroll down (" .. (#keys - layout.endIdx) .. " more) v")
        y = y + 1
      end

      y = layout.actionsHeaderY
      term.setCursorPos(1, y)
      term.setTextColor(colors.yellow)
      term.write(" ACTIONS (Tap to trigger):")
      y = y + 1

      local actList = getEntityActions(inspectEntity)
      if #actList == 0 then
        term.setCursorPos(2, y)
        term.setTextColor(colors.gray)
        term.write("(no actions available)")
        y = y + 1
      else
        for idx, act in ipairs(actList) do
          if y >= h - 1 then break end
          term.setCursorPos(2, y)
          term.setBackgroundColor(colors.gray)
          term.setTextColor(colors.white)
          term.write(padLine((" [%d] %s "):format(idx, act), w - 3))
          term.setBackgroundColor(colors.black)
          y = y + 1
        end
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "SETTINGS" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" SETTINGS & MANAGEMENT", w))

    term.setCursorPos(1, 3)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    term.write(padLine((" Metrics (%d)"):format(#cfg.metrics), w - 1))
    term.setBackgroundColor(colors.gray)
    term.write(">")

    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    term.write(padLine((" Quick Actions (%d)"):format(#cfg.quickActions), w - 1))
    term.setBackgroundColor(colors.gray)
    term.write(">")

    term.setCursorPos(1, 6)
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.lightGray)
    term.write(padLine(" Network", w))

    term.setCursorPos(1, 7)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.white)
    term.write(padLine(" Re-Sync Broker", w))

    term.setCursorPos(1, 8)
    term.setBackgroundColor(colors.red)
    term.setTextColor(colors.white)
    term.write(padLine(" Clear All Config", w))

    for r = 9, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "SETTINGS_METRICS" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" DASHBOARD METRICS", w))

    term.setCursorPos(1, 3)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    term.write(padLine(" [+] Add Metric", w))

    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.white)
    term.write(padLine(" [<] Back to Settings", w))

    local y = 6
    if #cfg.metrics == 0 then
      term.setCursorPos(2, y)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("(no metrics configured)")
      y = y + 1
    else
      for idx, m in ipairs(cfg.metrics) do
        if y >= h - 2 then break end
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.black)
        term.setTextColor(colors.cyan)
        local nick = (m.label or m.entity):sub(1, 6)
        term.write(nick .. string.rep(" ", math.max(1, 7 - #nick)))

        term.setTextColor(colors.lightGray)
        local keyText = (m.entity .. "." .. m.key)
        term.write(keyText:sub(1, math.max(1, w - 15)))

        term.setCursorPos(w - 7, y)
        term.setBackgroundColor(colors.blue)
        term.setTextColor(colors.white)
        term.write("[N]")
        term.setBackgroundColor(colors.red)
        term.setTextColor(colors.white)
        term.write(" [X]")
        term.setBackgroundColor(colors.black)
        y = y + 1
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "SETTINGS_ACTIONS" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" QUICK ACTIONS", w))

    term.setCursorPos(1, 3)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    term.write(padLine(" [+] Add Quick Action", w))

    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.white)
    term.write(padLine(" [<] Back to Settings", w))

    local y = 6
    if #cfg.quickActions == 0 then
      term.setCursorPos(2, y)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("(no quick actions configured)")
      y = y + 1
    else
      for idx, qa in ipairs(cfg.quickActions) do
        if y >= h - 2 then break end
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.black)
        term.setTextColor(colors.white)
        local aText = padLine(("%d. %s -> %s"):format(idx, qa.label or qa.action, qa.entity), w - 4)
        term.write(aText)
        term.setBackgroundColor(colors.red)
        term.setTextColor(colors.white)
        term.write(" [X]")
        term.setBackgroundColor(colors.black)
        y = y + 1
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "WIZARD_ENTITY" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" SELECT ENTITY:", w))

    local sorted = getSortedEntities()

    local y = 3
    if #sorted == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("No entities discovered yet.")
    else
      for idx, name in ipairs(sorted) do
        if y >= h - 2 then break end
        local actCount = #getEntityActions(name)
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.gray)
        term.setTextColor(colors.white)
        local itemText = (" [%d] %s"):format(idx, name)
        if wizardTarget == "ACTION" then
          itemText = itemText .. (" (%d acts)"):format(actCount)
        end
        term.write(padLine(itemText, w))
        term.setBackgroundColor(colors.black)
        y = y + 1
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "WIZARD_FIELD" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" SELECT FIELD FOR " .. tostring(wizardEntity) .. ":", w))

    local fields = getEntityFields(wizardEntity)

    local y = 3
    if #fields == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("No fields available.")
    else
      for idx, fKey in ipairs(fields) do
        if y >= h - 2 then break end
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.gray)
        term.setTextColor(colors.white)
        term.write(padLine((" [%d] %s"):format(idx, fKey), w))
        term.setBackgroundColor(colors.black)
        y = y + 1
      end
    end

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "WIZARD_ACTION" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" SELECT ACTION FOR " .. tostring(wizardEntity) .. ":", w))

    local actList = getEntityActions(wizardEntity)
    local y = 3
    if #actList == 0 then
      term.setCursorPos(2, 4)
      term.setBackgroundColor(colors.black)
      term.setTextColor(colors.gray)
      term.write("No actions defined for entity.")
      y = y + 2
    else
      for idx, act in ipairs(actList) do
        if y >= h - 3 then break end
        term.setCursorPos(1, y)
        term.setBackgroundColor(colors.gray)
        term.setTextColor(colors.white)
        term.write(padLine((" [%d] %s"):format(idx, act), w))
        term.setBackgroundColor(colors.black)
        y = y + 1
      end
    end

    -- Custom action option at bottom
    term.setCursorPos(1, y)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.white)
    term.write(padLine(" [*] Enter Custom Action...", w))
    term.setBackgroundColor(colors.black)
    y = y + 1

    for r = y, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "INPUT_ACTION_NAME" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" NEW CUSTOM ACTION", w))

    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.write("Entity: " .. tostring(wizardEntity))

    term.setCursorPos(1, 6)
    term.setTextColor(colors.yellow)
    term.write("Enter action name:")

    term.setCursorPos(1, 8)
    term.setTextColor(colors.white)
    term.write(" > " .. inputBuffer .. "_")

    for r = 9, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "INPUT_ARG" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(wizardCustomAction and " NEW QUICK ACTION" or " TRIGGER ACTION", w))

    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.white)
    term.write("Action: " .. tostring(selectedAction))

    term.setCursorPos(1, 6)
    term.setTextColor(colors.yellow)
    term.write("Enter arguments (or blank):")

    term.setCursorPos(1, 8)
    term.setTextColor(colors.white)
    term.write(" > " .. inputBuffer .. "_")

    for r = 9, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end

  elseif activeTab == "RENAME_METRIC" then
    term.setCursorPos(1, 2)
    term.setBackgroundColor(colors.gray)
    term.setTextColor(colors.yellow)
    term.write(padLine(" RENAME METRIC NICKNAME", w))

    local target = cfg.metrics[editMetricIdx]
    term.setCursorPos(1, 4)
    term.setBackgroundColor(colors.black)
    term.setTextColor(colors.cyan)
    term.write("Metric: " .. (target and (target.entity .. "." .. target.key) or "?"))

    term.setCursorPos(1, 6)
    term.setTextColor(colors.yellow)
    term.write("Enter short nickname (max 6):")

    term.setCursorPos(1, 8)
    term.setTextColor(colors.white)
    term.write(" > " .. inputBuffer .. "_")

    for r = 9, h - 2 do
      term.setCursorPos(1, r)
      term.setBackgroundColor(colors.black)
      term.write(string.rep(" ", w))
    end
  end

  -- Status Banner Line (Line h-1)
  term.setCursorPos(1, h - 1)
  if statusBanner then
    term.setBackgroundColor(colors.black)
    term.setTextColor(statusBanner.error and colors.red or colors.lime)
    term.write(padLine((statusBanner.error and "[!] " or "[*] ") .. statusBanner.text, w))
  else
    term.setBackgroundColor(colors.black)
    term.write(string.rep(" ", w))
  end

  -- Bottom Tab Bar (Line h)
  term.setCursorPos(1, h)
  term.setBackgroundColor(colors.gray)
  term.setTextColor(colors.white)

  local cfgGroup = {
    SETTINGS = true, SETTINGS_METRICS = true, SETTINGS_ACTIONS = true,
    WIZARD_ENTITY = true, WIZARD_FIELD = true, WIZARD_ACTION = true,
    INPUT_ACTION_NAME = true, RENAME_METRIC = true, INPUT_ARG = true,
  }

  local function drawTab(isActive, label, startX, endX)
    term.setCursorPos(startX, h)
    if isActive then
      term.setBackgroundColor(colors.blue)
      term.setTextColor(colors.yellow)
    else
      term.setBackgroundColor(colors.gray)
      term.setTextColor(colors.white)
    end
    term.write(label)
  end

  drawTab(activeTab == "DASHBOARD", " Dash ", 1, 6)
  drawTab(activeTab == "ACTIONS",   " Act  ", 7, 12)
  drawTab(activeTab == "ENTITIES" or activeTab == "INSPECT", " Ent  ", 13, 18)
  drawTab(cfgGroup[activeTab] or false, " Cfg  ", 19, 26)
end

--------------------------------------------------------------------
-- touch & key event handling
--------------------------------------------------------------------
local function handleTouch(x, y)
  local w, h = term.getSize()

  -- Bottom Tab Bar Touch
  if y == h then
    if x <= 6 then activeTab = "DASHBOARD"
    elseif x <= 12 then activeTab = "ACTIONS"
    elseif x <= 18 then activeTab = "ENTITIES"
    else activeTab = "SETTINGS" end
    renderScreen()
    return
  end

  if activeTab == "ACTIONS" then
    local btnIdx = math.floor((y - 3) / 2) + 1
    if btnIdx >= 1 and btnIdx <= #cfg.quickActions then
      local qa = cfg.quickActions[btnIdx]
      sendCommand(qa.entity, qa.action, qa.args)
      setBanner(("Sent '%s' to %s"):format(qa.action, qa.entity), false)
      renderScreen()
    end

  elseif activeTab == "ENTITIES" then
    local sorted = getSortedEntities()
    local rowIdx = y - 2
    if rowIdx >= 1 and rowIdx <= #sorted then
      inspectEntity = sorted[rowIdx]
      inspectScroll = 1
      activeTab = "INSPECT"
      renderScreen()
    end

  elseif activeTab == "INSPECT" then
    local layout = computeInspectLayout(inspectEntity)
    local keys = layout.keys

    -- Scroll tap buttons
    if y == 4 and layout.scrollUpShown then
      inspectScroll = math.max(1, inspectScroll - 1)
      renderScreen()
      return
    end

    if y == layout.scrollDownY and layout.scrollDownShown then
      inspectScroll = inspectScroll + 1
      renderScreen()
      return
    end

    -- Pin to Dash: only when the tap actually lands on the [+Dash] button
    -- (previously any tap on the row pinned the field, even scroll-adjacent misclicks)
    local valRowIdx = y - layout.valStartY + 1
    if x >= w - 5 and valRowIdx >= 1 and valRowIdx <= layout.rowsDrawn then
      local keyIdx = inspectScroll + valRowIdx - 1
      if keys[keyIdx] then
        local k = keys[keyIdx]
        cfg.metrics[#cfg.metrics + 1] = {
          entity = inspectEntity,
          key = k,
          label = inspectEntity .. "." .. k
        }
        saveConfig()
        setBanner(("Pinned %s.%s to Dash!"):format(inspectEntity, k), false)
        renderScreen()
        return
      end
    end

    -- Actions touch handling
    local actList = getEntityActions(inspectEntity)
    if #actList > 0 then
      local actStartY = layout.actStartY
      local actIdx = y - actStartY + 1
      if actIdx >= 1 and actIdx <= #actList then
        local actName = actList[actIdx]
        term.setBackgroundColor(colors.black)
        term.clear()
        term.setCursorPos(1, 2)
        term.setBackgroundColor(colors.gray)
        term.setTextColor(colors.yellow)
        term.write(padLine(" TRIGGER ACTION: " .. actName, w))
        term.setBackgroundColor(colors.black)
        term.setCursorPos(1, 4)
        term.setTextColor(colors.yellow)
        term.write("Enter args (blank for none):")
        term.setCursorPos(1, 6)
        term.setTextColor(colors.white)
        term.write("> ")
        local input = read()
        local parsed = input
        if not input or input == "" then parsed = nil
        elseif tonumber(input) then parsed = tonumber(input)
        elseif input:lower() == "true" then parsed = true
        elseif input:lower() == "false" then parsed = false end

        sendCommand(inspectEntity, actName, parsed)
        setBanner(("Sent '%s' to %s"):format(actName, inspectEntity), false)
        renderScreen()
      end
    end

  elseif activeTab == "SETTINGS" then
    if y == 3 then
      activeTab = "SETTINGS_METRICS"
      renderScreen()

    elseif y == 4 then
      activeTab = "SETTINGS_ACTIONS"
      renderScreen()

    elseif y == 7 then
      subscribe()
      requestRegistry()
      setBanner("Broker re-sync requested", false)
      renderScreen()

    elseif y == 8 then
      cfg.metrics = {}
      cfg.quickActions = {}
      saveConfig()
      setBanner("Config cleared", false)
      renderScreen()
    end

  elseif activeTab == "SETTINGS_METRICS" then
    if y == 3 then
      wizardTarget = "METRIC"
      activeTab = "WIZARD_ENTITY"
      renderScreen()

    elseif y == 4 then
      activeTab = "SETTINGS"
      renderScreen()

    elseif y >= 6 then
      local idx = y - 6 + 1
      if cfg.metrics[idx] then
        if x >= w - 4 then
          local removed = table.remove(cfg.metrics, idx)
          saveConfig()
          setBanner("Removed metric: " .. (removed.label or (removed.entity .. "." .. removed.key)), false)
          renderScreen()
        elseif x >= w - 8 then
          editMetricIdx = idx
          inputBuffer = ""
          activeTab = "RENAME_METRIC"
          renderScreen()
        end
      end
    end

  elseif activeTab == "SETTINGS_ACTIONS" then
    if y == 3 then
      wizardTarget = "ACTION"
      activeTab = "WIZARD_ENTITY"
      renderScreen()

    elseif y == 4 then
      activeTab = "SETTINGS"
      renderScreen()

    elseif y >= 6 then
      local idx = y - 6 + 1
      if cfg.quickActions[idx] then
        local removed = table.remove(cfg.quickActions, idx)
        saveConfig()
        setBanner("Removed action: " .. (removed.label or removed.action), false)
        renderScreen()
      end
    end

  elseif activeTab == "WIZARD_ENTITY" then
    local sorted = getSortedEntities()

    local entIdx = y - 2
    if entIdx >= 1 and entIdx <= #sorted then
      wizardEntity = sorted[entIdx]
      if wizardTarget == "METRIC" then
        activeTab = "WIZARD_FIELD"
      else
        activeTab = "WIZARD_ACTION"
      end
      renderScreen()
    end

  elseif activeTab == "WIZARD_FIELD" then
    local fields = getEntityFields(wizardEntity)

    local fIdx = y - 2
    if fIdx >= 1 and fIdx <= #fields then
      local selField = fields[fIdx]
      cfg.metrics[#cfg.metrics + 1] = {
        entity = wizardEntity,
        key = selField,
        label = wizardEntity .. "." .. selField
      }
      saveConfig()
      setBanner(("Added metric: %s.%s"):format(wizardEntity, selField), false)
      activeTab = "SETTINGS_METRICS"
      renderScreen()
    end

  elseif activeTab == "WIZARD_ACTION" then
    local actList = getEntityActions(wizardEntity)
    local aIdx = y - 2
    if aIdx >= 1 and aIdx <= #actList then
      local selAct = actList[aIdx]
      cfg.quickActions[#cfg.quickActions + 1] = {
        entity = wizardEntity,
        action = selAct,
        label = selAct:upper() .. " " .. wizardEntity:upper()
      }
      saveConfig()
      setBanner(("Added action: %s on %s"):format(selAct, wizardEntity), false)
      activeTab = "SETTINGS_ACTIONS"
      renderScreen()
    elseif aIdx == #actList + 1 or (#actList == 0 and y >= 4) then
      wizardCustomAction = true
      inputBuffer = ""
      activeTab = "INPUT_ACTION_NAME"
      renderScreen()
    end
  end
end

--------------------------------------------------------------------
-- main loop
--------------------------------------------------------------------
loadConfig()

term.clear()
term.setCursorPos(1, 1)
term.setTextColor(colors.yellow)
print("[Updater] Checking GitHub for updates...")

local ok, updated, reason = pcall(updater.checkAndApplySync)
if ok then
  if updated then
    print("[Updater] Update applied! Rebooting...")
    return
  elseif reason == "check failed" then
    printError("[Updater] couldn't reach GitHub - skipping this check")
  elseif reason ~= "http disabled" then
    -- "http disabled" already printed its own explanation above - saying
    -- "up to date" on top of that would be actively misleading, since it
    -- never actually checked
    print(("[Updater] Up to date (v:%s)"):format(updater.getShortVer(updater.currentVersion)))
  end
else
  printError("[Updater] Update check error: " .. tostring(updated))
end

sleep(0.5)

findBroker()
subscribe()
requestRegistry()

renderScreen()

local animTimer = os.startTimer(0.5)

while true do
  local ev = { os.pullEvent() }

  if ev[1] == "timer" and ev[2] == animTimer then
    animIdx = (animIdx % #animFrames) + 1
    animTimer = os.startTimer(0.5)
    -- selective light redraw of header animation only (zero flicker)
    term.setCursorPos(3, 1)
    term.setBackgroundColor(colors.blue)
    term.setTextColor(colors.yellow)
    term.write(animFrames[animIdx])

  elseif ev[1] == "mouse_click" or ev[1] == "touch" then
    handleTouch(ev[3], ev[4])

  elseif ev[1] == "mouse_scroll" and activeTab == "INSPECT" then
    local dir = ev[2]
    if dir < 0 then
      inspectScroll = math.max(1, inspectScroll - 1)
    else
      inspectScroll = inspectScroll + 1
    end
    renderScreen()

  elseif ev[1] == "char" and (activeTab == "INPUT_ARG" or activeTab == "RENAME_METRIC" or activeTab == "INPUT_ACTION_NAME") then
    if activeTab == "RENAME_METRIC" and #inputBuffer >= 6 then
      -- max 6 chars for label
    else
      inputBuffer = inputBuffer .. ev[2]
      renderScreen()
    end

  elseif ev[1] == "key" then
    local key = ev[2]
    if activeTab == "INSPECT" then
      if key == keys.up or key == keys.w then
        inspectScroll = math.max(1, inspectScroll - 1)
        renderScreen()
      elseif key == keys.down or key == keys.s then
        inspectScroll = inspectScroll + 1
        renderScreen()
      end
    elseif activeTab == "RENAME_METRIC" then
      if key == keys.backspace then
        inputBuffer = inputBuffer:sub(1, -2)
        renderScreen()
      elseif key == keys.enter then
        if editMetricIdx and cfg.metrics[editMetricIdx] then
          cfg.metrics[editMetricIdx].label = inputBuffer ~= "" and inputBuffer or nil
          saveConfig()
          setBanner("Metric nickname updated!", false)
        end
        activeTab = "SETTINGS_METRICS"
        renderScreen()
      -- Tab, not Escape: Minecraft eats Escape to close the terminal/pocket
      -- computer GUI before it ever reaches CC:Tweaked as a "key" event,
      -- and letters must stay typeable here, so no letter key can double
      -- as "cancel".
      elseif key == keys.tab then
        activeTab = "SETTINGS_METRICS"
        renderScreen()
      end

    elseif activeTab == "INPUT_ACTION_NAME" then
      if key == keys.backspace then
        inputBuffer = inputBuffer:sub(1, -2)
        renderScreen()
      elseif key == keys.enter then
        if inputBuffer ~= "" then
          selectedAction = inputBuffer
          inputBuffer = ""
          activeTab = "INPUT_ARG"
        end
        renderScreen()
      elseif key == keys.tab then
        wizardCustomAction = false
        activeTab = "WIZARD_ACTION"
        renderScreen()
      end

    elseif activeTab == "INPUT_ARG" then
      if key == keys.backspace then
        inputBuffer = inputBuffer:sub(1, -2)
        renderScreen()

      elseif key == keys.enter then
        local parsed = inputBuffer
        if inputBuffer == "" then parsed = nil
        elseif tonumber(inputBuffer) then parsed = tonumber(inputBuffer)
        elseif inputBuffer:lower() == "true" then parsed = true
        elseif inputBuffer:lower() == "false" then parsed = false end

        if wizardCustomAction then
          cfg.quickActions[#cfg.quickActions + 1] = {
            entity = wizardEntity,
            action = selectedAction,
            args = parsed,
            label = selectedAction:upper() .. " " .. wizardEntity:upper()
          }
          saveConfig()
          setBanner(("Added custom action: %s on %s"):format(selectedAction, wizardEntity), false)
          wizardCustomAction = false
          activeTab = "SETTINGS_ACTIONS"
        else
          sendCommand(inspectEntity, selectedAction, parsed)
          setBanner(("Sent '%s' to %s"):format(selectedAction, inspectEntity), false)
          activeTab = "INSPECT"
        end
        renderScreen()

      elseif key == keys.tab then
        if wizardCustomAction then
          wizardCustomAction = false
          activeTab = "SETTINGS_ACTIONS"
        else
          activeTab = "INSPECT"
        end
        renderScreen()
      end
    end

  elseif ev[1] == "rednet_message" and ev[4] == PROTOCOL then
    pcall(handleNet, ev[3], ev[2])
    renderScreen()
  end
end
