#!/usr/bin/env python3
"""
Regenerates VERSION.md and appends one row to VERSION_HISTORY.md for the
current commit. Run by .github/workflows/version-history.yml on every push
to main; can also be run locally (from a normal clone) to preview the
output before it's committed.

Why this exists: broker/provider/subscriber/controller/tablet all
auto-update from main (see checkForUpdate() in each script) and each
reports its running version as a short hash. Normally that's the first 7
characters of the real commit SHA, which you can already resolve directly
on GitHub. But if a computer's GitHub commit-API check failed when it last
updated (rate limited, offline, ...), it falls back to fetching the raw
file and hashing its *content* instead - an 8-character checksum that has
no relationship to git history at all. This script records both forms for
every commit, so any hash a computer displays can be traced back here
regardless of which path produced it.
"""
import os
import subprocess
from datetime import datetime, timezone

SCRIPTS = ["broker.lua", "provider.lua", "subscriber.lua", "controller.lua", "tablet.lua"]
REPO = os.environ.get("GITHUB_REPOSITORY", "PrimeAPI/cc-mqtt")


def fallback_hash(data: bytes) -> str:
    # Must match the Lua fallback in checkForUpdate()/checkAndApplyUpdate()
    # exactly (see e.g. broker.lua):
    #   local hash = 0
    #   for i = 1, #code do hash = (hash * 31 + code:byte(i)) % 4294967296 end
    #   remoteSha = string.format("%08x", hash)
    # Lua's numbers are doubles, but every intermediate value here stays
    # within 32 bits (well under 2^53), so the arithmetic is exact and this
    # produces a bit-identical result to the Lua version.
    h = 0
    for b in data:
        h = (h * 31 + b) % 4294967296
    return format(h, "08x")


def commit_sha() -> str:
    sha = os.environ.get("GITHUB_SHA")
    if sha:
        return sha
    return subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()


def main():
    sha = commit_sha()
    short = sha[:7]
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    hashes = {}
    for f in SCRIPTS:
        if os.path.exists(f):
            with open(f, "rb") as fh:
                hashes[f] = fallback_hash(fh.read())

    commit_link = f"[`{short}`](https://github.com/{REPO}/commit/{sha})"

    version_md = [
        "# Current deployed version",
        "",
        "Auto-generated by [.github/workflows/version-history.yml]"
        "(.github/workflows/version-history.yml) on every push to `main` - do not edit by hand.",
        "",
        f"- **Commit:** {commit_link}",
        f"- **Short hash shown on computers (normal path):** `{short}`",
        f"- **Recorded:** {date}",
        "",
        "## Fallback content hashes",
        "",
        "Shown instead of the commit hash by a computer whose GitHub API check failed and "
        "fell back to hashing the raw file it downloaded. Not a git SHA - look it up here, "
        "not on GitHub.",
        "",
        "| Script | Fallback hash | As displayed (7 chars) |",
        "|---|---|---|",
    ]
    for f in SCRIPTS:
        h = hashes.get(f, "?")
        version_md.append(f"| {f} | `{h}` | `{h[:7]}` |")
    version_md += ["", "See [VERSION_HISTORY.md](VERSION_HISTORY.md) for every previous commit."]

    with open("VERSION.md", "w") as fh:
        fh.write("\n".join(version_md) + "\n")

    header = (
        "# Version history\n\n"
        "Append-only log of every commit pushed to `main`, auto-generated by "
        "[.github/workflows/version-history.yml](.github/workflows/version-history.yml).\n\n"
        "Look up a hash a computer shows you: it's either the first 7 characters of the "
        "**Commit** column (or open `https://github.com/" + REPO + "/commit/<hash>` directly), "
        "or - if that computer's last GitHub API check failed - the first 7 characters of that "
        "script's **fallback hash** column instead.\n\n"
        "| Date (UTC) | Commit | broker.lua | provider.lua | subscriber.lua | controller.lua | tablet.lua |\n"
        "|---|---|---|---|---|---|---|\n"
    )
    row = "| {date} | {commit} | `{b}` | `{p}` | `{s}` | `{c}` | `{t}` |\n".format(
        date=date,
        commit=commit_link,
        b=hashes.get("broker.lua", "?"),
        p=hashes.get("provider.lua", "?"),
        s=hashes.get("subscriber.lua", "?"),
        c=hashes.get("controller.lua", "?"),
        t=hashes.get("tablet.lua", "?"),
    )

    if not os.path.exists("VERSION_HISTORY.md"):
        with open("VERSION_HISTORY.md", "w") as fh:
            fh.write(header)

    with open("VERSION_HISTORY.md", "a") as fh:
        fh.write(row)

    print(f"Recorded {short} ({date})")


if __name__ == "__main__":
    main()
